// An array of people, generated by ChatGPT.
const people = [
  {
    firstName: "Ash",
    lastName: "Ketchum",
    emailAddress: "ash.ketchum@example.com",
    phoneNumbers: [
      { type: "home", number: "123-456-7890" },
      { type: "mobile", number: "987-654-3210" },
    ],
  },
  {
    firstName: "Misty",
    lastName: "Waterflower",
    emailAddress: "misty.waterflower@example.com",
    phoneNumbers: [
      { type: "home", number: "111-222-3333" },
      { type: "office", number: "444-555-6666" },
    ],
  },
  {
    firstName: "Brock",
    lastName: "Rockwell",
    emailAddress: "brock.rockwell@example.com",
    phoneNumbers: [{ type: "mobile", number: "555-123-4567" }],
  },
  {
    firstName: "Serena",
    lastName: "Lumière",
    emailAddress: "serena.lumiere@example.com",
    phoneNumbers: [{ type: "home", number: "777-888-9999" }],
  },
  {
    firstName: "Gary",
    lastName: "Oak",
    emailAddress: "gary.oak@example.com",
    phoneNumbers: [{ type: "office", number: "333-444-5555" }],
  },
  {
    firstName: "May",
    lastName: "Maple",
    emailAddress: "may.maple@example.com",
    phoneNumbers: [{ type: "mobile", number: "999-888-7777" }],
  },
  {
    firstName: "Dawn",
    lastName: "Skye",
    emailAddress: "dawn.skye@example.com",
    phoneNumbers: [{ type: "home", number: "222-333-4444" }],
  },
  {
    firstName: "Cilan",
    lastName: "Sage",
    emailAddress: "cilan.sage@example.com",
    phoneNumbers: [{ type: "office", number: "444-555-6666" }],
  },
  {
    firstName: "Lillie",
    lastName: "Moon",
    emailAddress: "lillie.moon@example.com",
    phoneNumbers: [{ type: "mobile", number: "777-888-9999" }],
  },
  {
    firstName: "Kiawe",
    lastName: "Flame",
    emailAddress: "kiawe.flame@example.com",
    phoneNumbers: [{ type: "home", number: "111-222-3333" }],
  },
];

// console.log(people);

// Find the tbody in the HTML page using querySelector
const tbody = document.querySelector(".person-table > tbody");

// Calls the addPeopleRows function below to add all person rows to the tbody
addPeopleRows(people, tbody);

/**
 * This function adds new rows to the given tbody, containing the information about the given people.
 *
 * @param people the person whose data should be displayed in the table body
 * @param tbody the table body element.
 */
function addPeopleRows(people, tbody) {
  /**
   * Use array's forEach function to loop thru all people in the array, and call the given
   * arrow function for each one. The arrow function will in turn call the addPersonRow() function below.
   *
   * The result is that the addPersonRow() function will be called once for each person in the array.
   */
  people.forEach((person) => addPersonRow(person, tbody));
}

/**
 * This function adds a new row to the given tbody, containing the information about the given person.
 *
 * @param person the person whose data should be displayed in the new row.
 * @param {HTMLElement} tbody the table body element.
 */
function addPersonRow(person, tbody) {
  // Create new row
  const row = document.createElement("tr");

  // Add first name, last name, and email cells using the createTextCell function defined below.
  row.appendChild(createTextCell(person.firstName));
  row.appendChild(createTextCell(person.lastName));
  row.appendChild(createTextCell(person.emailAddress));

  // Create a td containing an ul, which will hold our phone numbers. Append to the tr above.
  const phoneCell = document.createElement("td");
  row.appendChild(phoneCell);
  const phoneList = document.createElement("ul");
  phoneCell.appendChild(phoneList);

  // Loop thru phone numbers using for - of syntax
  for (const phoneNumber of person.phoneNumbers) {
    phoneList.innerHTML += `<li><strong>${phoneNumber.type}:</strong> ${phoneNumber.number}</li>`;
  }

  // Append row to tbody
  tbody.appendChild(row);
}

/**
 * Creates and returns a new table cell with the given text content.
 *
 * @param {string} textContent the text in the cell
 */
function createTextCell(textContent) {
  const td = document.createElement("td");
  td.textContent = textContent;
  return td;
}








// 由人工智能生成的“人员”对象数组。
const people = [
  {
    firstName: "小智",
    lastName: "阿罗拉",
    emailAddress: "ash.ketchum@example.com",
    phoneNumbers: [
      { type: "住宅", number: "123-456-7890" },
      { type: "手机", number: "987-654-3210" },
    ],
  },
  {
    firstName: "小霞",
    lastName: "华蓝",
    emailAddress: "misty.waterflower@example.com",
    phoneNumbers: [
      { type: "住宅", number: "111-222-3333" },
      { type: "办公", number: "444-555-6666" },
    ],
  },
  // ... 其他人员数据省略 ...
];

// 使用 querySelector 在 HTML 页面中找到表格主体 (tbody)
const tbody = document.querySelector(".person-table > tbody");

// 调用下方的 addPeopleRows 函数，将所有人的人员行添加到 tbody 中
addPeopleRows(people, tbody);

/**
 * 此函数向给定的 tbody 添加新行，包含给定人员数组的信息。
 *
 * @param people 要在表格中显示的人员数据数组
 * @param tbody 表格主体元素
 */
function addPeopleRows(people, tbody) {
  /**
   * 使用数组的 forEach 函数循环遍历数组中的所有人，
   * 并为每个人调用一次给出的箭头函数。
   * 该箭头函数随后会调用 addPersonRow() 函数。
   *
   * 结果就是：数组中的每个人都会触发一次 addPersonRow() 调用。
   */
  people.forEach((person) => addPersonRow(person, tbody));
}

/**
 * 此函数向给定的 tbody 添加一个新行 (tr)，包含单个人员的信息。
 *
 * @param person 要在新行中显示的人员数据对象
 * @param {HTMLElement} tbody 表格主体元素
 */
function addPersonRow(person, tbody) {
  // 创建新行 (tr)
  const row = document.createElement("tr");

  // 使用下方定义的 createTextCell 函数添加名字、姓氏和邮箱单元格。
  row.appendChild(createTextCell(person.firstName));
  row.appendChild(createTextCell(person.lastName));
  row.appendChild(createTextCell(person.emailAddress));

  // 创建一个包含 <ul> 的单元格 (td)，用于存放电话号码。
  // 然后将其添加到上面创建的行中。
  const phoneCell = document.createElement("td");
  row.appendChild(phoneCell);
  const phoneList = document.createElement("ul");
  phoneCell.appendChild(phoneList);

  // 使用 for...of 语法循环遍历电话号码数组
  for (const phoneNumber of person.phoneNumbers) {
    phoneList.innerHTML += `<li><strong>${phoneNumber.type}:</strong> ${phoneNumber.number}</li>`;
  }

  // 最后将完整的行添加到 tbody 中
  tbody.appendChild(row);
}

/**
 * 创建并返回一个带有给定文本内容的新表格单元格 (td)。
 *
 * @param {string} textContent 单元格内的文本内容
 */
function createTextCell(textContent) {
  const td = document.createElement("td");
  td.textContent = textContent;
  return td;
}